### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by fipp** [spgill/stock-hound#1]
Do you accept pull requests to this project? E.g. for extending the hound to support europe?

**Comment by spgill** [comment]
Hey @fipp ! Thanks for the star!

I'm not currently accepting pull requests.

I'm in the middle of rewriting the application front-end using material-ui right now. Mainly for the purpose of enhancing the user experience, but I'm also using it as an opportunity to revise the privacy policy to make it compatible with Europe with the goal of adding support for European IKEA markets.

I'll definitely keep you in mind when it comes time to test out support for Europe, though. 😁
