### ISSUE TITLE
United Kingdom not listed as country

### ISSUE THREAD

**Issue by JayGeorge** [spgill/stock-hound#2]
Hey Samuel,

It would be great if the United Kingdom was listed in the countries. Not sure if this simply isn't possible or whether you forgot to include it in the list. Many thanks.

**Comment by tantalusblank** [comment]
+1 to the above - this would be incredibly handy if it also included the UK

**Comment by spgill** [comment]
Previously didn't list the UK because its site had subtle differences that broke the API... but that was awhile ago

Just delivered and published a major update that, among other things, introduces some new countries to the app; including the United Kingdom.

Thanks for opening this issue 😄
