### ISSUE TITLE
Stock Hound failing to fetch product name

### ISSUE THREAD

**Issue by gene1wood** [spgill/stock-hound#4]
# Steps to reproduce

1. Enter the product code for Billy : `802.638.32` in country `US`, store `CA, Emeryville`

# Expected results

To get an email that says 
```
You have created a new reminder for Billy, article number 802.638.32 at the CA, Emeryville store.
```

# Actual results

An email that says

```
You have created a new reminder for False , article number 802.638.32 at the CA, Emeryville store.
```

**Comment by spgill** [comment]
Just delivered and published a major update that, among other things, removes the product name from the email. The existing code was too unreliable to keep due to API changes.

Thanks for opening this issue 😄
